### ISSUE TITLE
Download individual article from a Journal

### ISSUE THREAD

**Issue by LlGC-szw** [UniversalViewer/user-stories#2] opened 2017-10-27 08:04 UTC
## So that I can limit my digital copy to the pages where the article I require appears

**Comment by LlGC-szw** [comment] 2017-10-27 08:06
Currently all articles for that issue appear in the download box 

http://universalviewer.io/uv.html?manifest=http://www.llgc.org.uk/rhannu/1371518-y-ford-gron.json

**Comment by LlGC-szw** [comment] 2017-10-27 08:22
Possible UI:
![download_box_mockup_01](https://user-images.githubusercontent.com/10922825/32094626-540a90ba-baf8-11e7-8f29-29c687265c46.png)

**Comment by LlGC-szw** [comment] 2017-11-07 13:35
Updated example: http://universalviewer.io/uv.html?manifest=https://www.llgc.org.uk/rhannu/TestCcymod1319153.json

**Comment by tomcrane** [comment] 2017-11-07 16:38
At the moment, all the articles appear in the download menu all the time because they are all `rendering` properties of the sequence:

![image](https://user-images.githubusercontent.com/1443575/32504926-e05fd91a-c3d8-11e7-974f-dffe56db305e.png)

The current data in the manifest shows that you already have the PDFs for the individual articles. So one way of doing this would be to create ranges in the manifest for each article, and attach the individual article PDF to its correct range, via a `rendering` property on the range. The UV's download menu would then need to be context-sensitive for the `range` the current page belongs to, so it could offer just that range's PDF:

( ) Download ISSUE (pdf)
( ) Download THIS ARTICLE (pdf)

That would require some new development.

The other approach (which is the one suggested in your "possible UI" screen shot) is that the user selects the pages. This is what the BL do - the next step in your screen shot is a selection screen showing thumbs with checkboxes. The BL implement this by having a server process that generates the PDF from the supplied list of canvas IDs. The UV is configured to pass the selected list to the service.

The latter requires nothing new in the UV as it already allows configuration to enable this option (but you would need to implement the service that generates the PDF from the list of canvases). The former does need some new development, to make the download menu context-sensitive to the current range. You would also need to publish manifests with range information in them, with the rendering property pointing at the correct PDF for each range.

Which of these is your preferred approach?

Tom

**Comment by tomcrane** [comment] 2017-11-07 16:39
ping @edsilv to sanity-check the above ^^

**Comment by LlGC-szw** [comment] 2017-11-07 16:47
We would want the articles to be pre-defined as downloads so the user doesn't have to know which pages are part of an article  which is why we didn't want to just offer the facility to select multiple pages. The per article download is part of the MVP and the BL-style select isn't (as we don't have the pdf generation service yet).

**Comment by tomcrane** [comment] 2017-11-07 16:51
OK, so the new development required in the UV is the context sensitive download behaviour for ranges. And for you, adding the ranges to the manifest, with rendering properties.

**Comment by ioanrichards** [comment] 2017-11-08 17:12
Hi Tom, thank you for your advice on how the manifest should look ready for development.  I've created a manifest (attached), do you mind having a look to see if we're on the right track please?  

Ignore the minimal canvas information within 'sequences', our disseminators adds the information when a manifest is requested and this manifest was generated through a XML editor.

[RangesTest1319153.txt](https://github.com/UniversalViewer/user-stories/files/1454730/RangesTest1319153.txt)

**Comment by tomcrane** [comment] 2017-11-13 17:19
Hi @ioanrichards 

You don't need `viewingHint: top` on all the ranges. You can have it on one range, which would then include its child ranges via a further `ranges` property (or `members` property if the children are a mix of ranges and canvases). For the current use case I don't think you need the viewingHint at all, as you don't have any nesting.

The `rendering` properties are OK, although as there is only one rendering you don't need the value to be an array of objects, just the object.

In your example the ranges all have the same `@id` but I assume that's just a testing artefact. They need different IDs.

By the way this will look a lot cleaner in the Presentation API v3!

**Comment by tomcrane** [comment] 2017-11-13 17:20
Also - you can test the ranges in the UV if you make a manifest with canvases. It won't show the download options for them, but you can check that your range structure is correct.

**Comment by ioanrichards** [comment] 2017-11-14 11:21
Picked up on the array ([ ]) last week and removed them.  I've now completely removed the viewingHint.  The above was a test, I've now applied unique IDs for the ranges.  Thank you for your feedback.

**Comment by ioanrichards** [comment] 2017-11-14 11:31
Latest manifest.

[TestCcymod1319153.txt](https://github.com/UniversalViewer/user-stories/files/1470559/TestCcymod1319153.txt)

**Comment by edsilv** [comment] 2017-11-23 10:04
Hi @LlGC-szw 

Could you check this please? http://universalviewer.io/examples/#?c=0&m=0&s=0&cv=0&manifest=https%3A%2F%2Fedsilv.github.io%2Ftest-manifests%2Frange-renderings.json&xywh=-1284%2C-1%2C6088%2C4494

**Comment by LlGC-szw** [comment] 2017-11-23 11:50
Looks good to us so far. We just need to load a bilingual manifest onto the server so we can test if that displays the correct text. We should be able to do that today/tomorrow.

**Comment by LlGC-szw** [comment] 2017-11-28 12:02
Just to update you, we have staff off sick at the moment so no access to a manifest for testing.

**Comment by ioanrichards** [comment] 2017-12-01 10:13
I can't seem to get the bilingual functionality working, can anybody spot anything wrong with the Json:

{{{
"sequences": [{
        "@id": "http://dams.llgc.org.uk/iiif/2.0/2176035/sequence/physical.json",
        "@type": "sc:Sequence",
        "label": "Current Page Order",
        "viewingDirection": "left-to-right",
        "viewingHint": "paged",
        "rendering": {
            "@id": "http://datasyllwr.llgc.org.uk/2176035.pdf",
            "format": "application/pdf",
            "label": [
                {
                    "@value": "Download Llyfr I Ionawr 1895 PDF",
                    "@language": "en"
                },
                {
                    "@value": "Lawrlwytho Llyfr I Ionawr 1895 PDF",
                    "@language": "cy-GB"
                }
            ]
        },
}}}

**Comment by LlGC-dwj** [comment] 2017-12-01 22:30
Hi Ed, we've collated some feedback for you of the work so far:

Download box: The pdf labels always display in English
Download box: The terms of use goes to the wrong field for us - needs to be the license field
More information panel: the license field picks up the English value
More information panel: the repository field picks up the English value

The last 2 might be more v3 related than this work, do you want me to open a ticket for them?

Thanks,
Dylan

**Comment by edsilv** [comment] 2017-12-02 12:19
I've pushed a fix for the pdf labels to get translated.

I've also pushed a fix to pick up the license field if available for the terms dialogue, and fall back to attribution. I seem to remember attribution being used by design though @irv ? However, you have your license field in `metadata`, not as a root-level property as per the spec, so it won't get found.

There appears to be something wrong with the metadata component where it's not using the correct translation for certain values. More time needed to look into this.

**Comment by irv** [comment] 2017-12-03 13:15
based on the description in the spec  http://iiif.io/api/presentation/2.1/#rights-and-licensing-properties `attribution` should probably be the default if present (as it *MUST* be shown) with fallback to `license`.

Although why not both if available?

**Comment by LlGC-szw** [comment] 2017-12-04 09:36
The demo links are:

http://universalviewer.io/examples/#?c=0&m=0&s=0&cv=0&manifest=http%3A%2F%2Fwww.llgc.org.uk%2Frhannu%2FTestScif2176035.json&xywh=-1447%2C-94%2C5049%2C3726 

and 

http://universalviewer.io/examples/#?c=0&m=0&s=0&cv=0&manifest=http%3A%2F%2Fwww.llgc.org.uk%2Frhannu%2FTestCcymod1319153.json&xywh=-1622%2C-250%2C6765%2C4993

**Comment by LlGC-szw** [comment] 2017-12-04 09:40
The translation is showing up in the download box now but the 'more information' panel still has the English only. Shall I add this as a separate issue?

**Comment by edsilv** [comment] 2017-12-05 09:43
I've created one here: https://github.com/UniversalViewer/universalviewer/issues/519

**Comment by hackartisan** [comment] 2018-03-21 16:47
UniversalViewer/user-stories#2

Estimate: 2 days
Added by tomcrane

**Closed as completed** 2018-10-04 09:22 UTC
